//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TaskTracker.rc
//
#define IDR_APPICON                     2
#define IDR_APPMENU                     3
#define IDR_APPACCEL                    4
#define IDR_APPTOOLBAR                  5
#define IDR_TRAYMENU                    6
#define ID_FILE_POPUP                   100
#define ID_FILE_EXPORT                  101
#define ID_FILE_IMPORT                  102
#define ID_FILE_EXIT                    103
#define ID_SESSION_POPUP                200
#define ID_SESSION_CLOCK_IN             201
#define ID_SESSION_SWITCH_TASKS         202
#define ID_SESSION_CLOCK_OUT            203
#define ID_SESSION_EDIT                 204
#define ID_REPORT_POPUP                 300
#define ID_REPORT_WINDOW                301
#define ID_REPORT_CLIPBOARD             302
#define ID_REPORT_PRINT                 303
#define ID_REPORT_FILE                  304
#define ID_PRUNE_POPUP                  400
#define ID_PRUNE_SESSIONS               401
#define ID_PRUNE_TASKS                  402
#define ID_PRUNE_LOCNS                  403
#define ID_TOOLS_POPUP                  800
#define ID_TOOLS_OPTIONS                801
#define ID_HELP_POPUP                   900
#define ID_HELP_ABOUT                   902
#define ID_TRAY_RESTORE                 1001
#define IDC_CURRENT_TIME                1001
#define ID_TRAY_EXIT                    1002
#define IDC_CURRENT_DATE                1002
#define IDC_NOW                         1003
#define IDC_SESSION_DATE                1004
#define IDC_ON_AT                       1005
#define IDC_SESSION_TIME                1006
#define IDC_DATE                        1007
#define IDC_SESSION_LEN                 1008
#define IDC_SESSION_TASK                1010
#define IDC_TO_DATE                     1011
#define IDC_TASK                        1012
#define IDC_TOTAL_TODAY                 1013
#define IDC_LOCN                        1013
#define IDC_PREV_TASK                   1014
#define IDC_TOTAL_WEEK                  1015
#define IDC_NEXT_TASK                   1017
#define IDC_TOTAL_MONTH                 1018
#define IDC_TOTAL_TOTAL                 1020
#define IDC_SESSIONS                    1021
#define IDC_ADD                         1022
#define IDC_MODIFY                      1023
#define IDC_DELETE                      1025
#define IDC_RENAME                      1026
#define IDC_ALL                         1027
#define IDC_BEFORE                      1028
#define IDC_PRINTER                     1029
#define IDC_PORT                        1030
#define IDC_BROWSE                      1035
#define IDC_FILENAME                    1036
#define IDC_TASKS                       1037
#define IDC_SELECT                      1038
#define IDC_FROM_DATE                   1042
#define IDC_PERIOD                      1046
#define IDC_GROUP_NONE                  1050
#define IDC_GROUP_WEEK                  1051
#define IDC_GROUP_MONTH                 1052
#define IDC_GROUP_TASK                  1053
#define IDC_REPORT                      1054
#define IDC_DATETIME                    1055
#define IDC_OUT_DATETIME                1056
#define IDC_IN_DATETIME                 1057
#define IDC_LOCNS                       1059
#define IDC_MIN_TO_TRAY                 1060
#define IDC_SESSION_HDR                 1061
#define IDC_TOTAL_HDR                   1062
#define IDC_LEN_FORMAT                  1063
#define IDC_OVERLAP                     1064
#define IDC_WEEK_ORDER                  1065
#define IDC_OLD_TASK                    1065
#define IDC_NEW_TASK                    1066
#define IDC_WEBSITE                     1083
#define IDC_EMAIL                       1084
#define IDC_VERSION                     1085
#define IDC_REMEMBER                    1086
#define IDD_MAIN                        5000
#define IDD_ABOUT                       5001
#define IDD_CLOCK_IN                    5002
#define IDD_CLOCK_OUT                   5003
#define IDD_SWITCH_TASKS                5004
#define IDD_EDIT_SESSIONS               5005
#define IDD_ADD_SESSION                 5006
#define IDD_MODIFY_SESSION              5007
#define IDD_PRUNE_SESSIONS              5008
#define IDD_FILE_REPORT                 5009
#define IDD_PRINT_REPORT                5010
#define IDD_PRUNE_TASKS                 5011
#define IDD_PRUNE_LOCNS                 5012
#define IDD_CLPWND_REPORT               5013
#define IDD_VIEW_REPORT                 5014
#define IDD_OPTIONS                     5015
#define IDD_EXPORT                      5016
#define IDD_IMPORT                      5017
#define IDD_RENAME                      5018
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        119
#define _APS_NEXT_COMMAND_VALUE         117
#define _APS_NEXT_CONTROL_VALUE         1067
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
